version: '3.8'

services:
  web:
    build: .
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=host.docker.internal
      - S3_ENDPOINT_URL=https://9f2f990f3b48601a6b91e239e06b7f17.r2.cloudflarestorage.com
      - S3_REGION=auto
      - S3_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=waterdepoimages
      - S3_PUBLIC_DOMAIN=${R2_PUBLIC_DOMAIN}